name: GRAINBESPOKE
favicon: null
layout_spectrum: 0.18716
typography_spectrum: 0.55669
title: GRAIN BESPOKE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e121b'
    - '#222c38'
    - '#34404e'
    - '#4b5767'
    - '#636f7f'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
