name: GRAINBESPOKE
favicon: null
layout_spectrum: 0.260004467330873
typography_spectrum: 0.7330413311719894
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.642563165165484
  lightness: 0.6101477628108114
  saturation: 0.9638221103232354
  rhythmicContrast: 0.8678949277382344
purpose: []
